Refresh homepage
canonical/microstack.run pull request #214
Opened 2023-01-10 17:06 UTC by petesfrench

## Done

- Refreshes homepage based on changes in the [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)

## QA

- Go to and compare against [copydoc](https://docs.google.com/document/d/1-QO5zAclj469qGvFmNJBjQ_qqI_T_uliwj6mAo8ZbCs/edit#)
- Check that all six individual tabs work and don't interfere with each other

## Issue / Card

Fixes https://github.com/canonical/web-squad/issues/6311

2023-01-10 17:06 UTC, webteam-app commented
Demo starting at https://microstack-run-214.demos.haus

2023-01-11 10:44 UTC, anthonydillon requested changes
Good work @petesfrench. A few comments in the code.

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +            <strong>Note:</strong> MicroStack is in a beta state. We encourage you to test it, share your <a href="https://microstack.run/survey">feedback</a> and <a href="https://discourse.juju.is/s
Could you use the [Information Notification](https://vanillaframework.io/docs/patterns/notification#information) pattern here please?

2023-01-11 10:44 UTC, anthonydillon commented on templates/partial/_navigation.html
> +            <a class="p-navigation__link" href="https://discourse.charmhub.io/search?q=microstack">Get community help</a>
```suggestion
            <a class="p-navigation__link" href="https://discourse.charmhub.io/tag/microstack">Get community help</a>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +            <strong>Note:</strong> MicroStack is in a beta state. We encourage you to test it, share your <a href="https://microstack.run/survey">feedback</a> and <a href="https://discourse.juju.is/s
```suggestion
            <strong>Note:</strong> MicroStack is in a beta state. We encourage you to test it, share your <a href="https://microstack.run/survey">feedback</a> and <a href="https://discourse.charmhub.io/tag/microstack">ask questions</a>. For commercial support, <a href="https://ubuntu.com/openstack/contact-us">contact us directly</a>.
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +        <p>MicroStack is the most straightforward OpenStack ever. It installs in minutes through a friendly interface, making OpenStack fully accessible to those with no previous experience. Just <a
There is no link in the copy doc.

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
>          <h3 class="u-align--center" style="margin-left: 1.5rem; margin-right: 1.5rem;">~1,500 active installations</h3>
You don't need the inline styles here

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
>          <h3 class="u-align--center" style="margin-left: 1.5rem; margin-right: 1.5rem;">~1,500 active installations</h3>
Is this a header of a p with a heading class?

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +        <p>Designed for devices with minimal hardware resources, MicroStack is perfectly suitable for developer workstations and <a href="/engage/devops-cicd-webinar">CI/CD</a> environments.</p>
```suggestion
        <p>Designed for devices with minimal hardware resources, MicroStack is perfectly suitable for developer workstations and <a href="https://ubuntu.com/engage/devops-cicd-webinar">CI/CD</a> environments.</p>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +          <a href="/openstack/features">For large-scale deployments, try Charmed OpenStack&nbsp;&rsaquo;</a>
```suggestion
          <a href="https://ubuntu.com/openstack/features">For large-scale deployments, try Charmed OpenStack&nbsp;&rsaquo;</a>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +          <a href="/engage/public-cloud-openstack-implementation">Watch a webinar about public cloud implementation&nbsp;&rsaquo;</a>
```suggestion
          <a href="https://ubuntu.com/engage/public-cloud-openstack-implementation">Watch a webinar about public cloud implementation&nbsp;&rsaquo;</a>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +          <a href="/engage/edge-infrastructure">Read a whitepaper about OpenStack on the edge&nbsp;&rsaquo;</a>
```suggestion
          <a href="https://ubuntu.com/engage/edge-infrastructure">Read a whitepaper about OpenStack on the edge&nbsp;&rsaquo;</a>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +        <p>Ideal to meet requirements in telecom, industrial, automotive and other market sectors that need <a href="/edge-computing">edge infrastructure</a>.</p>
```suggestion
        <p>Ideal to meet requirements in telecom, industrial, automotive and other market sectors that need <a href="https://ubuntu.com/edge-computing">edge infrastructure</a>.</p>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +                <a href="https://discourse.ubuntu.com/t/install-and-configure-microstack-sunbeam-single-node/32157" class="p-button--positive">Follow a tutorial</a>
Is this all? Seems there is more content but incomplete in the copy doc

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +                <a href="https://discourse.ubuntu.com/t/install-and-configure-microstack-sunbeam-single-node/32157" class="p-button--positive">Follow a tutorial</a>
Might want to check with @tytus-kurek if the instructions section is correct.

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +          <a href="/openstack/install">Get started with Charmed OpenStack&nbsp;&rsaquo;</a>
```suggestion
          <a href="https://openstack/install">Get started with Charmed OpenStack&nbsp;&rsaquo;</a>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +        <p><a href="/openstack/features">Try Charmed OpenStack</a>, a distribution that gives you total control of all OpenStack components and their permutations. Build your cloud from the ground up
```suggestion
        <p><a href="https://ubuntu.com/openstack/features">Try Charmed OpenStack</a>, a distribution that gives you total control of all OpenStack components and their permutations. Build your cloud from the ground up and tailor it to your needs.</p>
```

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +      </div>
You editor should strip whitepace on save

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +{% block title %}OpenStack on Kubernetes | Ubuntu{% endblock %}
This title is not updated, might be an issue with the base template

2023-01-11 10:44 UTC, anthonydillon commented on templates/index.html
> +MicroStack delivers distilled OpenStack excellence with native K8s experience. OCI images, Kubernetes operators, lucid interface - all you need to run fully functional OpenStack on Kubernetes with mi
Same here, check the base template is not hardcoded.

2023-01-11 10:54 UTC, lyubomir-popov commented
![image](https://user-images.githubusercontent.com/2741678/211788058-10dd116f-16e5-4193-a0a1-942b9807c3fd.png)
![image](https://user-images.githubusercontent.com/2741678/211788087-65b60e65-813e-4b8b-8136-02594b1af7e1.png)
![image](https://user-images.githubusercontent.com/2741678/211788108-719a9c84-e1f8-47b6-9060-37d8938b10a0.png)
are the above new additions, or already there? The stroke thickness varies a lot. If they were already there, then maybe we ca nfix this once planning unit provide an updated icon style. If we're adding any of these in this pr, I would suggest sending them to our current icon designer to conform stroke thicknesses.

2023-01-11 11:12 UTC, petesfrench commented on templates/partial/_navigation.html
> +            <a class="p-navigation__link" href="https://discourse.charmhub.io/search?q=microstack">Get community help</a>
I have updated the link to the one in the copydoc, is that all that was needed? I can't see any comments

2023-01-11 11:41 UTC, juanruitina commented
Two tweaks for better accessibility:

- Can you please add `Meet MicroStack - YouTube` as the `title` attribute for the video iframe?
- I see subtitles below some headings (e.g. "On your workstation; in your CI/CD environment") are `h3` elements, but technically they are not headings. Can you make them `p` elements instead? Styling still applies via the class, so it should be fine.

I noticed `MicroStack` is not properly capitalised in one instance, under "K8s-native architecture". I edited the copy doc to fix this.

Number of active installations has increased to "~2,300 active installations". Besides, I think that banner looks rather weak now that it is the single figure given as social proof. I wonder if something could be done at the visual level (@lyubomir-popov), or perhaps place the copy somewhere else and get rid of the banner altogether. E.g. we could incorporate it to the hero text, e.g. "Distilled upstream excellence with a native K8s experience. Already used in over 2,300 installations." What do you think?

2023-01-11 11:48 UTC, petesfrench commented
@lyubomir-popov These were mostly additions in this PR. Who is the person ask about this?

2023-01-11 11:56 UTC, petesfrench commented
Thanks @juanruitina, I have applied those changes. Tytus was also happy with removing the banner. Could you take another look and give it a +1 if you are happy?

2023-01-11 18:07 UTC, anthonydillon commented on templates/partial/_navigation.html
> +            <a class="p-navigation__link" href="https://discourse.charmhub.io/search?q=microstack">Get community help</a>
That is it.

2023-01-12 10:49 UTC, juanruitina commented
LGTM now!

2023-01-16 17:48 UTC, anthonydillon commented
Single QA question:
- [ ] Missing the "~2,300 active installations" section

2023-01-16 17:49 UTC, anthonydillon approved these changes
The code looks good with QA questions.

2023-01-17 08:56 UTC, petesfrench commented
> Single QA question:
> 
> * [x]  Missing the "~2,300 active installations" section

@anthonydillon It was agreed with Juan and Tytus to remove the banner, at least for now. I will add that information to the description.

2023-01-19 13:23 UTC, petesfrench commented
@lyubomir-popov I have updated the SVGs, can you take another look when you have time please?

2023-01-19 13:38 UTC, lyubomir-popov commented
Hi @petesfrench much better, two questions:
- are the images displayed at the actual size of the files? Most seem to be 250px tall, with some exceptions. If  those are the sizes then great.
- This one seems blurred - might be worth checking again 
![image](https://user-images.githubusercontent.com/2741678/213456840-54912567-8f67-473b-ad9b-bf888625965a.png)

2023-01-19 14:57 UTC, merged